Feature/id/1894/master
vivitainc/custom_cell_boards pull request #1
Opened 2021-02-15 09:34 UTC by dodo5522

2021-03-23 03:33 UTC, dodo5522 commented
@TomohiroHayashi すいません、後から思い出したんですが...　Pololu A-Starリポジトリベースの[328pb_bootloader](https://github.com/vivitainc/328pb_bootloader)を本リポジトリに統合しても問題ないですよね…？
328pb_bootloader側のタグバージョンを引き継ぎ、コミット履歴や何らかのstudy用ブランチは、同様の形で本リポジトリに再現するつもりでいます。

2021-03-23 04:22 UTC, TomohiroHayashi commented
> @TomohiroHayashi すいません、後から思い出したんですが...　Pololu A-Starリポジトリベースの[328pb_bootloader](https://github.com/vivitainc/328pb_bootloader)を本リポジトリに統合しても問題ないですよね…？
> 328pb_bootloader側のタグバージョンを引き継ぎ、コミット履歴や何らかのstudy用ブランチは、同様の形で本リポジトリに再現するつもりでいます。

@dodo5522 すみません、このPublicリポジトリの存在理由は `package_vivita_index.json` の置き場所と、それ以外の目的があるのでしたっけ？

2021-03-23 05:46 UTC, dodo5522 commented
@TomohiroHayashi ごめんなさい、説明が色々抜けてました。
当初の目論見は以下の通りでしたが、

- Arduino IDE Board Managerが参照、インストールするパッケージを本リポジトリで提供する
- 本リポジトリには以下を含む
    1. package_vivita_index.json (このjsonをBoard Managerが参照し、以下をパッケージとして提供する)
    2. boards/platform/programmers.txt
    3. bootloader binary files
    4. variants files (328pbピン定義ヘッダなど)

Pololu A-Starと同様、bootloaderバイナリとソースをboard定義と共に一元管理したいと思い、それに伴って 328pb_bootloaderはa-starリポジトリのコピーである https://github.com/vivitainc/328pb_bootloader と https://github.com/vivitainc/atmega_bootloader (公開用) に分離しているコードを、元々公開する必要がある本リポジトリに統合したいと考えました。

2021-03-23 06:19 UTC, TomohiroHayashi commented
@dodo5522 
> * Arduino IDE Board Managerが参照、インストールするパッケージを本リポジトリで提供する
> * 本リポジトリには以下を含む
>   
>   1. package_vivita_index.json (このjsonをBoard Managerが参照し、以下をパッケージとして提供する)
>   2. boards/platform/programmers.txt
>   3. bootloader binary files
>   4. variants files (328pbピン定義ヘッダなど)
> 
> Pololu A-Starと同様、bootloaderバイナリとソースをboard定義と共に一元管理したいと思い、それに伴って 328pb_bootloaderはa-starリポジトリのコピーである https://github.com/vivitainc/328pb_bootloader と https://github.com/vivitainc/atmega_bootloader (公開用) に分離しているコードを、元々公開する必要がある本リポジトリに統合したいと考えました。

なるほど…。実際使用しているbootloaderの
https://github.com/vivitainc/custom_cell_boards/tree/develop/bootloaders/atmega
は、Forkもとの https://github.com/pololu/a-star には存在しない（Arduinoインストールフォルダから自分が https://github.com/vivitainc/328pb_bootloader にコピーして改変したため）という背景があるのですが、このリポジトリでatmega bootloaderのGPLソースコードを公開・管理することに（ライセンス的に？）問題なければ、上記方針で良いと思います。
その方針の場合、Cell Appの中でファームウェアのGPLライセンスのソースコード公開場所として表示してもらっている https://github.com/vivitainc/atmega_bootloader のURLだけ変更する必要がありますね。

2021-03-23 07:32 UTC, dodo5522 commented
@TomohiroHayashi 
> Forkもとの https://github.com/pololu/a-star には存在しない（Arduinoインストールフォルダから自分が https://github.com/vivitainc/328pb_bootloader にコピーして改変したため）という背景があるのですが、このリポジトリでatmega bootloaderのGPLソースコードを公開・管理することに（ライセンス的に？）問題なければ、上記方針で良いと思います。

はい、Pololu提供のソースはa-star board config含め、基本MITライセンスなので、GPLコードを含めたことでMITを継承できなくても問題ないです。
ただ、元の条文は残します。bootloaders/caterinaもArduinoから持ってきたようで、[LICENSE.txt](https://github.com/pololu/a-star/blob/master/LICENSE.txt)にはPololuとcaterinaの両方を記載する形となっています。

> fbec9c3 - Copied Caterina bootloader files from Arduino. (7 years ago) <Kevin (Pololu)>

2021-03-23 07:35 UTC, dodo5522 commented
> その方針の場合、Cell Appの中でファームウェアのGPLライセンスのソースコード公開場所として表示してもらっている https://github.com/vivitainc/atmega_bootloader のURLだけ変更する必要がありますね。

確かに…　本PRと併せて対応中のPR https://github.com/vivitainc/branch_cell/pull/176 で変更します。

2021-03-23 07:46 UTC, TomohiroHayashi commented
@dodo5522 そう言えば、結局bootloaderだけでなく、 https://github.com/vivitainc/VivicoreSerial 自体もGPLv2扱いにする結論になったので、このソースコード公開場所もアプリで表示した方が良いですね…

2021-03-23 10:53 UTC, dodo5522 commented
@TomohiroHayashi 
> ソースコード公開場所もアプリで表示した方が良いですね…

OSSライセンス表示する場所がアプリくらいしかないですね、確かに。
Webアプリ系は必ずしも使うわけではないし…

2021-03-30 13:14 UTC, dodo5522 commented
@TomohiroHayashi 
https://github.com/vivitainc/branch_cell/pull/176 と併せて、レビューと動作確認をお願いします。
`build.sh` `flasher.sh` の修正差分が多めですが、ベースとしたbranch_cellと比較すると少なめです。

```diff
--- ../branch_cell/build.sh	2021-03-16 19:56:25.000000000 +0900
+++ build.sh	2021-03-30 22:11:59.000000000 +0900
@@ -14,6 +14,9 @@
 DIR_EX_LIB=externals
 DIR_OWN_LIB=VivicoreSerial
 DIR_WORKSPACE=_workspace
+WINAVR_GCC='WinAVR-20100110'
+DIR_WINAVR_GCC_BIN="/c/${WINAVR_GCC}/bin"
+DIR_TMP_HARDWARE_PACKAGE="${DIR_HARDWARE4}/0.0.1"
 
 DIR_SKETCH=sketch
 FW_BIN_SUFFIX="ino.bin"
@@ -81,7 +84,10 @@
 function Usage() {
   echo 
   echo "Usage: ${PROGNAME} [Options]"
-  echo 
+  echo
+  echo "Note: This script builds bootloader and applies them as ${DIR_TMP_HARDWARE_PACKAGE}."
+  echo "      Install again VIVIWARE board package after build with this script."
+  echo
   echo "Option: One of the options must be required"
   echo "  -h, --help              Help"
   echo "      --version           Show version"
@@ -267,6 +273,29 @@
   fi
 }
 
+function CompileBootloader() {
+  if ! [ -d "${DIR_WINAVR_GCC_BIN}" ]; then
+    echo "${WINAVR_GCC} must be instelled to compile bootloader"
+    exit 1
+  fi
+
+  make -C ${DIR_BOOTLOADER} TOOLCHAIN_PREFIX="${DIR_WINAVR_GCC_BIN}/" clean all
+  echo
+  echo "Built $(ls ${DIR_BOOTLOADER}/*.hex) for ATmega${MCU_UPPER} with $("${DIR_WINAVR_GCC_BIN}/avr-gcc" --version | head -n 1)"
+}
+
+function InstallLocalPackage() {
+  echo
+  echo "Uninstall all package for VIVIWARE in ${DIR_HARDWARE4}"
+  mkdir -p "${DIR_HARDWARE4}"
+  rm -rf "${DIR_HARDWARE4:?}"/*
+
+  echo
+  echo "Install package as ${DIR_TMP_HARDWARE_PACKAGE}"
+  mkdir -p "${DIR_TMP_HARDWARE_PACKAGE}"
+  cp -rf ./* "${DIR_TMP_HARDWARE_PACKAGE}"/
+}
+
 function CompileFirmware() {
   if [ $# -eq 0 ]; then
     echo "ComplileFirmware function needs an argument"
@@ -306,9 +335,13 @@
   if [ -e "${DIR_INO_ROOT}/${ino_name}/${DIR_BUILD}/${BUILD_OPTION_FILE}" ]; then
     rm "${DIR_INO_ROOT}/${ino_name}/${DIR_BUILD}/${BUILD_OPTION_FILE}"
   fi
+  # Specify workspace directory path including our own and external library
+  if [ ! -d "${DIR_WORKSPACE}" ]; then
+    DIR_WORKSPACE="${DIR_LIB}"
+  fi
 
   # Compile
-  echo "Building ${DIR_INO_PATH}/${ino_name}.ino for ATmega${MCU_UPPER}"
+  echo "Building ${DIR_INO_PATH}/${ino_name}.ino for ATmega${MCU_UPPER} with $(avr-gcc --version | head -n 1)"
 
   #echo arduino-builder -dump-prefs ${HARDWARE} ${TOOLS} -built-in-libraries "${DIR_BUILTIN_LIB}" -libraries "${DIR_WORKSPACE}" -fqbn="${BOARD_NAME}" -build-path "${DIR_ABS_BUILD_PATH}" -verbose ${DIR_INO_PATH}/${ino_name}.ino
   eval "arduino-builder -dump-prefs ${HARDWARE} ${TOOLS} -built-in-libraries \"${DIR_BUILTIN_LIB}\" -libraries \"${DIR_WORKSPACE}\" -fqbn=\"${BOARD_NAME}\" -build-path \"${DIR_ABS_BUILD_PATH}\" -verbose \"${DIR_INO_PATH}/${ino_name}.ino\"" 1> "${DIR_ABS_BUILD_PATH}/${BUILD_LOG_NAME}" 2> "${DIR_ABS_BUILD_PATH}/${BUILD_ERRLOG_NAME}"
@@ -368,17 +401,19 @@
 if [ -n "${flg_build_all}" ] || [ -n "${REL_INO_FILE}" ]; then
   # Copy root *.h *.cpp to ${DIR_WORKSPACE}
   #for lib_file in `\find . -maxdepth 1 -type f -name *.h | sed 's!^.*/!!'`; do
-  for lib_file in `ls -1 *.cpp *.h`; do
-    if [ ! -e "${DIR_WORKSPACE}/${DIR_OWN_LIB}" ]; then
+  for lib_file in *.cpp *.h; do
+    if [ -f "${lib_file}" ]; then
       mkdir -p "${DIR_WORKSPACE}/${DIR_OWN_LIB}"
+      cp "${lib_file}" "${DIR_WORKSPACE}/${DIR_OWN_LIB}"
+      echo "Copied ${lib_file} to ${DIR_WORKSPACE}/${DIR_OWN_LIB}"
     fi
-    cp "${lib_file}" "${DIR_WORKSPACE}/${DIR_OWN_LIB}"
-    echo "Copied ${lib_file} to ${DIR_WORKSPACE}/${DIR_OWN_LIB}"
   done
 
   # Copy libraries directory to ${DIR_WORKSPACE}
-  cp -R ${DIR_EX_LIB}/* "${DIR_WORKSPACE}/"
-  echo "Copied ${DIR_EX_LIB}/* to ${DIR_WORKSPACE}/"
+  if [ -d "${DIR_EX_LIB}" ]; then
+    cp -R ${DIR_EX_LIB}/* "${DIR_WORKSPACE}/"
+    echo "Copied ${DIR_EX_LIB}/* to ${DIR_WORKSPACE}/"
+  fi
 fi
 
 if [ -n "${FW_ARG}" ]; then
@@ -396,6 +431,14 @@
 fi
 #echo "LS_CMD=${LS_CMD}"
 
+# Clean, Compile, and apply bootloader
+if [ -n "${FW_ARG}" ] || [ -n "${flg_build_all}" ]; then
+  if [ -d "${DIR_BOOTLOADER}" ]; then
+    CompileBootloader
+    InstallLocalPackage
+  fi
+fi
+
 # Clean and Compile
 for ino_dir in `${LS_CMD}`; do
   if [ ! -d "${DIR_INO_ROOT}/$ino_dir" ]; then
@@ -409,6 +452,11 @@
   fi
 done
 
+# Clean bootloader and package
+if [ -d "${DIR_TMP_HARDWARE_PACKAGE}" ]; then
+  rm -rf "${DIR_TMP_HARDWARE_PACKAGE}"
+fi
+
 # Verify compile results
 if [ -n "${FW_ARG}" ] || [ -n "${flg_build_all}" ]; then
   echo
```

```diff
--- ../branch_cell/ArduinoFlasher/flasher.sh	2021-03-24 16:03:48.000000000 +0900
+++ ArduinoFlasher/flasher.sh	2021-03-30 22:11:59.000000000 +0900
@@ -49,10 +49,12 @@
 }
 
 function Usage() {
-  echo 
+  echo
   echo "Usage: ${PROGNAME} [Options]"
-  echo 
+  echo
   echo "Option: -p option must be required for Windows"
+  echo "        -f option is not set, then flash bootloader only"
+  echo
   echo "  -h                         Help"
   echo "  -p <port number or name>   Port number or name to Arduino ISP"
   echo "  -B <baudrate>              Set baudrate to talk with Arduino ISP (default: 19200)"
@@ -68,13 +70,9 @@
   local branchtype_line=$(grep -E "^const(expr){0,1}\s+uint32_t\s+BRANCH_TYPE" ${ino_file})
   local branchtype=$(echo "${branchtype_line}" | sed -e 's|^.*BRANCH_TYPE *= *0x\([0-9a-fA-F]\{1,\}\);.*|\1|')
 
-  echo ${branchtype}
+  echo ${branchtype:-0}
 }
 
-if [ $# = 0 ]; then
-  Usage
-fi
-
 while(( $# > 0 )); do
   case "$1" in
     - | --)
@@ -128,7 +126,7 @@
         done
       ;;
 
-    * ) 
+    * )
       echo "Unknown argument $1"
       Usage
   esac
@@ -150,7 +148,11 @@
 #echo "MCU_UPPER=${MCU_UPPER}"
 
 # Analysis ${FW_ARG} and create ${INO_DIR_NAME}, ${DIR_INO_ROOT}, ${REL_HEX_FILE} and ${REL_INO_FILE}
-if [ -n "${FW_ARG}" ]; then
+if [ -z "${FW_ARG}" ]; then
+  echo
+  echo 'Flash bootloader only'
+  echo
+else
   if [ -e "${FW_ARG}" ]; then
     if [ -f "${FW_ARG}" ] && [ ${FW_ARG##*.} = ino ]; then
       # If ${FW_ARG} is ino file full path
@@ -223,19 +225,30 @@
 _EOS_
 )
 
-
 if [ -z "$com" ]; then
   echo "Error: -p option must be required"
   exit
 fi
 
-DIR_INO_PATH=${DIR_INO_ROOT}/${INO_DIR_NAME}
-DIR_REL_BUILD_PATH=${DIR_INO_PATH}/${DIR_BUILD}
-if [ ! -e "${DIR_REL_BUILD_PATH}" ]; then
-  mkdir "${DIR_REL_BUILD_PATH}"
-fi
+if [ -z "${FW_ARG}" ]; then
+  # Flash
+  echo avrdude -C "${CONF1_FILE}" ${FORCE_OPTION} -v -p atmega${MCU_LOWER} -c stk500v1 -P ${PORT_PREFIX}${com} -b "${ISP_BAUDRATE}" -Uflash:w:${BOOTLOADER_SRC}
+  avrdude -C "${CONF1_FILE}" ${FORCE_OPTION} -v -p atmega${MCU_LOWER} -c stk500v1 -P ${PORT_PREFIX}${com} -b "${ISP_BAUDRATE}" -Uflash:w:${BOOTLOADER_SRC}:i
+  # Fuse
+  echo avrdude -C "${CONF1_FILE}" ${FORCE_OPTION} -v -D -p atmega${MCU_LOWER} -c stk500v1 -P ${PORT_PREFIX}${com} -b "${ISP_BAUDRATE}" -Ulock:w:0x2F:m -Uefuse:w:0xF5:m -Uhfuse:w:0xD2:m -Ulfuse:w:0xFF:m
+  avrdude -C "${CONF1_FILE}" ${FORCE_OPTION} -v -D -p atmega${MCU_LOWER} -c stk500v1 -P ${PORT_PREFIX}${com} -b "${ISP_BAUDRATE}" -Ulock:w:0x2F:m -Uefuse:w:0xF5:m -Uhfuse:w:0xD2:m -Ulfuse:w:0xFF:m
+
+  echo
+  echo "Successfully ${BOOTLOADER_SRC} flashed for ATmega${MCU_UPPER}."
+  exit 0
+else
+  DIR_INO_PATH=${DIR_INO_ROOT}/${INO_DIR_NAME}
+  DIR_REL_BUILD_PATH=${DIR_INO_PATH}/${DIR_BUILD}
+
+  if [ ! -e "${DIR_REL_BUILD_PATH}" ]; then
+    mkdir "${DIR_REL_BUILD_PATH}"
+  fi
 
-if [ -n "${FW_ARG}" ]; then
   if [ ! -e "${REL_HEX_FILE}" ]; then
     echo ${FW_ARG} not found
     ErrorMsg
@@ -314,7 +327,4 @@
   if [ -n "${BRANCH_TYPE}" ]; then
     echo "0x${BRANCH_TYPE} has been written into EEPROM"
   fi
-else
-  echo "Error: -f option must be required"
-  Usage
 fi
```

2021-03-31 01:52 UTC, TomohiroHayashi commented
@dodo5522 Git管理構造を変更しようとしている理由を見失いかけて迷子になっていますが、Fork元の  https://github.com/pololu/a-star から実際に引き継いでいるモノは何になるのでしたっけ？
↓のHistoryでは、5.0.0を境目に急にVersionの意味合いがatmegaboot対象に変わっているので、package_vivita_index.json などのバージョンとatmegabootのバージョンは切り離して考えたほうが良い気もしてきました…。
https://github.com/vivitainc/custom_cell_boards/tree/feature/id%2F1894%2Fmaster#version-history

2021-03-31 02:03 UTC, TomohiroHayashi commented
>    - bootloader単体でのビルド手順は `make -C bootloader/atmega` コマンド実行（または`cd bootloader/atmega`して`make`実行）に変更

`bootloader/atmega` -> `bootloaders/atmega` にPRコメント修正しました。

2021-03-31 02:32 UTC, dodo5522 commented
@TomohiroHayashi 
> Git管理構造を変更しようとしている理由を見失いかけて迷子になっていますが、

色々いっぺんにやってしまったので、複雑になってしまいすいません…

> Fork元の https://github.com/pololu/a-star から実際に引き継いでいるモノ

主に以下ですね。

- boards.txt
    - [L26-L32](https://github.com/vivitainc/custom_cell_boards/blob/feature/id/1894/master/boards.txt#L26-L32) は、pololu a-star版ほぼそのまま
    - pololu a-star以外のボード定義は全て削除し、a-starをcell-328pbに変更
    - menu.versionをVIVIWARE Custom/Branch向けオプションに変更
- platform.txt, programmers.txt
    - pololu a-star版ほぼそのまま
    - Arduino IDE同梱版に328pbが含まれるため、extra_avrdude.confを使用しないよう修正
- variants/cell-328pb
    - ディレクトリ名のみ変更
    - ファイルはpololu a-star版そのまま

> ↓のHistoryでは、5.0.0を境目に急にVersionの意味合いがatmegaboot対象に変わっているので、package_vivita_index.json などのバージョンとatmegabootのバージョンは切り離して考えたほうが良い気もしてきました…。

確かに、そこは結構悩んだんですが…　ベースにしたpololu a-starのバージョンタグと過去のバージョンタグ履歴も残したく、今の形にしちゃいました。
ただ、今後はbootloaderのバージョンは別途降り直して（5.4, 5.5, ..等）、package_vivita_index.json のバージョンはそれと連動することなく、リリースのタイミングでMajor.Minor.Patchをアサインするのが良さそうに思います。

2021-03-31 08:31 UTC, TomohiroHayashi requested changes
@dodo5522 とりあえず、 https://github.com/vivitainc/branch_cell/pull/176 で以下の方針になったことに伴い、boards.txt は変更が入ると思うので、一旦Request changesにします。

> BOARD_TYPE_CUSTOM/BOARD_TYPE_BRANCH のような汎用的な定義をboard package側から指定するように

2021-03-31 08:42 UTC, TomohiroHayashi commented
@dodo5522 
> ただ、今後はbootloaderのバージョンは別途降り直して（5.4, 5.5, ..等）、package_vivita_index.json のバージョンはそれと連動することなく、リリースのタイミングでMajor.Minor.Patchをアサインするのが良さそうに思います。

AtmegaBOOT のバージョンはソースコードの中にバージョン定義があるわけでもなく、[328pb_bootloader](https://github.com/vivitainc/328pb_bootloader/releases) リポジトリのGitでの管理の都合上、タグ名でかなり応急処置的に 5.0 からタグを打っただけなので、新たにリポジトリ再構成するなら、例えばもとの AtmegaBOOT を 1.0 扱いで、次にVIVITA変更最新版を 2.0 などにしても良いのですが、どうするのがベストですかね？
いまの[このリポジトリのタグ](https://github.com/vivitainc/custom_cell_boards/releases)が5.0以降二重構成になっているのが気になっています…

2021-03-31 08:59 UTC, dodo5522 commented
@TomohiroHayashi 
> 例えばもとの AtmegaBOOT を 1.0 扱いで、次にVIVITA変更最新版を 2.0 などにしても良い

それも良いかと思ったんですが、branch_cellリポジトリのコミット履歴に`v5.x`等の記載 [8eb9ffc - v5.3 bootloader: GPIO0 |= 1 ...](https://github.com/vivitainc/branch_cell/commit/8eb9ffc) が残っているので、対応表を別途用意するのも避けたいんですよね…

> いまの[このリポジトリのタグ](https://github.com/vivitainc/custom_cell_boards/releases)が5.0以降二重構成になっているのが気になっています…

うう、確かに。。

2021-03-31 09:14 UTC, dodo5522 commented
@TomohiroHayashi 
応急処置だったこともあり、328pb_bootloader v5系はそもそものバージョニングフォーマットも異なるので特別扱いにして、以下のようにするのはどうでしょう？

- v4.x.x : Pololu A-Star board package + bootloader
- v5.x : VIVIWARE bootloader only
    - v5.x.xタグは削除する
- v6.x.x : VIVIWARE board package + bootloader
    - bootloaderを変更した場合は、その影響度に応じてMajor.Minor.Patchを更新する
    - bootloader固有のバージョンは今後付与しない
    - [version history](https://github.com/vivitainc/custom_cell_boards/tree/feature/id/1894/master#version-history)のv6.0.0には、v5.3 bootloader includedの旨を記載する

2021-03-31 11:04 UTC, TomohiroHayashi commented
@dodo5522 
> 応急処置だったこともあり、328pb_bootloader v5系はそもそものバージョニングフォーマットも異なるので特別扱いにして、以下のようにするのはどうでしょう？
> 
> * v4.x.x : Pololu A-Star board package + bootloader
> * v5.x : VIVIWARE bootloader only
>   
>   * v5.x.xタグは削除する
> * v6.x.x : VIVIWARE board package + bootloader
>   
>   * bootloaderを変更した場合は、その影響度に応じてMajor.Minor.Patchを更新する
>   * bootloader固有のバージョンは今後付与しない
>   * [version history](https://github.com/vivitainc/custom_cell_boards/tree/feature/id/1894/master#version-history)のv6.0.0には、v5.3 bootloader includedの旨を記載する

うーん、それも一案ですかね…。
ところで `Major.Minor.Patch` のフォマットはArduino board packageのバージョニングルールとして規定されている内容なのでしょうか？
[二重構成のタグ](https://github.com/vivitainc/custom_cell_boards/releases)になるくらいなら、もとの `Major.Minor` だけのタグは消してもらっても良いのですが…

> branch_cellリポジトリのコミット履歴にv5.x等の記載 8eb9ffc - v5.3 bootloader: GPIO0 |= 1 ... が残っているので、対応表を別途用意するのも避けたいんですよね…

この点はコミットメッセージだけ修正して、バージョン記述を消しても良いのですが…

とか色々と考え出すと、ATmegaBOOTの履歴としては本来 [328pb_bootloader](https://github.com/vivitainc/atmega_bootloader) リポジトリの方が由緒正しいのでこれをPrivateにして内部管理用に残しつつ、custom_cell_boards リポジトリでは公開用として最新のVIVIWARE Cell bootloaderを追加し、bootloaderの管理ではなくboard package管理用として、5.0.0 or 6.0.0からタグ付与するのはどうでしょう？

bootloaderの修正は、今後もほぼないと考えられるので、仮に発生した場合は、この公開リポジトリへのコミットは手動で十分だと思います。

※そう言えば、最後の `GPIO0 |= 1 to notify firmware app` の修正を [328pb_bootloader](https://github.com/vivitainc/atmega_bootloader) にまだ入れてなかったですね…

2021-03-31 12:04 UTC, dodo5522 commented
@TomohiroHayashi 
> これをPrivateにして内部管理用に残しつつ、custom_cell_boards リポジトリでは公開用として最新のVIVIWARE Cell bootloaderを追加し、bootloaderの管理ではなくboard package管理用として、5.0.0 or 6.0.0からタグ付与するのはどうでしょう？
> ※そう言えば、最後の `GPIO0 |= 1 to notify firmware app` の修正を [atmega_bootloader](https://github.com/vivitainc/atmega_bootloader) にまだ入れてなかったですね…

(↑リンクはあってましたが、 `atmega_bootloader` にコメント変更しました)
そうしましょう！
atmega_bootloaderに最新をコミットしてタグ付けします。

2021-03-31 12:55 UTC, dodo5522 commented
@TomohiroHayashi 
> ところで Major.Minor.Patch のフォマットはArduino board packageのバージョニングルールとして規定されている内容なのでしょうか？

回答漏れてました。
はい、バージョンはsemver2に準拠すべき、とLibrary Manager、Board  Manager共に記載があります。

https://arduino.github.io/arduino-cli/latest/package_index_json-specification/#platforms-definitions
> The version field is validated by both Arduino IDE and JSemVer. (JSemVerは結局semver2準拠)

https://arduino.github.io/arduino-cli/latest/library-specification/#15-library-format-rev-22
> version of the library. Version should be semver compliant.

2021-03-31 15:33 UTC, dodo5522 commented
@TomohiroHayashi 
> board package管理用として、5.0.0 or 6.0.0からタグ付与する

(すいません、本PRのブランチにいくつかforce pushして歴史改変しました…)
5.3.0で既にインストール済みの人がいる可能性あるため、6.0.0から開始することにしました。

2021-04-01 05:34 UTC, TomohiroHayashi approved these changes
@dodo5522 このリポジトリまるごとBoard Managerで配布されてしまうので 325780d で更に不要なファイルを消しました。念のため確認お願いできますか？
これらのファイルはバージョン管理不要だと思うので、[328pb_bootloader](https://github.com/vivitainc/328pb_bootloader)リポジトリを消す前に、Google Driveにでも移動してしまおうと思います。

2021-04-01 06:06 UTC, dodo5522 commented
@TomohiroHayashi はい、問題ないです。マージお願いします。

2021-04-01 06:08 UTC, dodo5522 commented
@TomohiroHayashi あ、すいません、READMEのVersion Historyを更新し忘れたので、少々お待ちを…

2021-04-01 06:15 UTC, dodo5522 commented
@TomohiroHayashi 7f716fc にて更新しました。問題なければマージお願いします。

2021-04-01 06:32 UTC, TomohiroHayashi commented on README.md
> +- 6.0.0 (2021-04-01): Add [328PB ATmega bootloader v5.3](https://github.com/vivitainc/atmega_bootloader/releases/tag/5.3)
@dodo5522 すみません、ここに [atmega_bootloader](https://github.com/vivitainc/atmega_bootloader) へのリンクを書くと、[atmega_bootloader](https://github.com/vivitainc/atmega_bootloader)はPrivateにせずにPublicのままキープすることになりますが（それ自体はその方針でも良いですが）、その場合は ATmegaBOOT_168.c のソースコードを２個のPublicリポジトリで二重管理することにならないでしょうか？
個人的にはタグの履歴としては以下のようなニュアンスで良いと思っていました。

```suggestion
- 6.0.0 (2021-04-01): Add customized ATmegaBOOT
```

2021-04-01 06:33 UTC, dodo5522 commented on README.md
> +- 6.0.0 (2021-04-01): Add [328PB ATmega bootloader v5.3](https://github.com/vivitainc/atmega_bootloader/releases/tag/5.3)
@TomohiroHayashi すいません、うっかりしてました。。

> これをPrivateにして内部管理用に残しつつ

なので、上記修正で問題ないです。

2021-04-01 06:36 UTC, TomohiroHayashi commented
修正ありがとうございます。マージします。

2021-04-01 06:37 UTC, merged

2021-04-01 06:38 UTC, TomohiroHayashi commented
@dodo5522 もしや自動delete設定してくれてます？

2021-04-01 06:41 UTC, dodo5522 commented
@TomohiroHayashi あ、そうでした。
![スクリーンショット 2021-04-01 15 39 46](https://user-images.githubusercontent.com/1362607/113253710-98eec500-9300-11eb-9755-eb3bf8c8f4fa.png)

A-Starをfork時にSettingsを調整した際、設定してみたんでした。

2021-04-01 06:42 UTC, dodo5522 commented
core_cellやbranch_cellも自動Delete設定にしますかね…

2021-04-01 06:43 UTC, TomohiroHayashi commented
@dodo5522 良いですね！branch_cell とか core_cell で試そうとしたことがあるのですが、例えばdevelop->masterマージでdevelopが消えたりすると嫌だなと思ったので…

2021-04-01 06:46 UTC, dodo5522 commented
@TomohiroHayashi 確かにそれが心配だったんですが、ベースブランチは削除できないっぽいんですよね。
develop->masterマージPRでも、deleteボタンが出現しませんし…

2021-04-01 06:48 UTC, TomohiroHayashi commented
@dodo5522 あとはstageブランチとかの存在も懸念だったのですが、マージ元ブランチは基本的には自動削除でOKですかね…？

2021-04-01 06:51 UTC, dodo5522 commented
@TomohiroHayashi あーー　PRでstage/fp1/developをstage/fp1/masterにマージしたら、多分stage/fp1/developは自動削除対象ですね…。featureブランチは基本自動削除でOKですが…

2021-04-01 06:53 UTC, dodo5522 commented
@TomohiroHayashi 
> 多分stage/fp1/developは自動削除対象

これ↓で設定できそうな気がしますね。

> Branch protection rules
Define branch protection rules to disable force pushing, prevent branches from being deleted, and optionally require status checks before merging.

2021-04-01 06:54 UTC, dodo5522 commented
branch_cellやcore_cellの前に、他で色々試してみます。

2021-04-01 06:54 UTC, TomohiroHayashi commented
@dodo5522 そうですね…。そのルールでちゃんと保護しておけばOKだと思います。間違えて削除発動した場合もRestoreできれば問題ないかと…

2021-04-01 07:01 UTC, TomohiroHayashi commented
@dodo5522 あと、このリポジトリで `refs #` は機能してないですね。
https://support.vivita.io/projects/vivi-parts-firmware/settings/repositories
の設定の前にサーバーにcloneしてもらう必要がありましたっけ？

2021-04-01 07:02 UTC, TomohiroHayashi commented
Publicリポジトリなので必要ないという意見もありますかね…

2021-04-01 07:05 UTC, dodo5522 commented
@TomohiroHayashi 
> 設定の前にサーバーにcloneしてもらう必要がありましたっけ？

依頼し忘れてました…　redmine稼働サーバ上で `/opt/repos/xxx.git`  等にcloneしておいてもらう必要がありますね。
redmineが参照できない一般の方からすると、refs番号がgithub上のissue/pr番号とは紐づかないので、疑問に思われるかもしれませんが…

2021-04-01 07:07 UTC, TomohiroHayashi commented
@dodo5522 
> redmineが参照できない一般の方からすると、refs番号がgithub上のissue/pr番号とは紐づかないので、疑問に思われるかもしれませんが…

そうなんですよね…。今後も頻度高くメンテが必要ならclone・設定した方が良いかもですが、どうですかね？

2021-04-01 07:11 UTC, dodo5522 commented
@TomohiroHayashi 今回スイッチを汎用的なBRANCH_TYPE_xxにしたこともあり、今後更新することはあまりないはずなので、一旦無しで、もし次更新することがあればその時設定してもらう、で問題ないと思います。

2021-04-01 07:14 UTC, TomohiroHayashi commented
@dodo5522 そうですね。自分もそう思います。

2021-04-01 07:16 UTC, dodo5522 commented
では、このリポジトリに関しては、一旦現状のままということで…

2021-04-01 08:01 UTC, dodo5522 commented
@TomohiroHayashi 
branch protection rulesは、この設定↓でいけそうです。
https://github.com/vivitainc/custom_cell_boards/settings/branches

以下のパターンにマッチするブランチのAllow deletionsをOFFにしています。
- `*` (e.g. `master` `develop`)
- `stage/**/*` (e.g. `stage/fp1/develop`)

[About branch protection rules](https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule#about-branch-protection-rules)によると、パターンマッチは古い方が優先度高いようですが、今回はdeleteを禁止したいブランチ名のfnmatchパターンが被らないので、どちらを先にしても同様にdelete禁止できます。

https://github.com/vivitainc/custom_cell_boards/branches でゴミ箱がグレーアウト表示のブランチは、PRマージ後のauto deletionも機能しないですね。
- https://github.com/vivitainc/custom_cell_boards/pull/2
    - featureブランチのマージ後、マージ元ブランチは自動削除される
- https://github.com/vivitainc/custom_cell_boards/pull/3
    - stage/fp1/developをstage/fp1/masterにマージ後、マージ元ブランチは自動削除されない

2021-04-01 09:26 UTC, TomohiroHayashi commented
@dodo5522 なるほど…。調査ありがとうございます。同様の設定すれば、core/branch_cell にも適用できそうですね。

2021-04-01 13:24 UTC, dodo5522 commented
@TomohiroHayashi 
本リポジトリのテスト用`stage/**/*`ブランチは削除しました。

core/branch_cellリポジトリのAllow deletions除外設定をした上で、
https://github.com/vivitainc/core_cell/settings/branches
https://github.com/vivitainc/branch_cell/settings/branches

PRマージ後のAuto deleteをONに、ついでにマージボタンのsquash, rebase選択肢をOFFにしました。
![スクリーンショット 2021-04-01 22 17 22](https://user-images.githubusercontent.com/1362607/113299673-13870700-9338-11eb-93d4-0768ed9eb136.png)

2021-04-01 13:28 UTC, TomohiroHayashi commented
@dodo5522 ありがとうございます。